#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=dwifid
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

if [ "$(id -u)" -ne "0" ]
then
	echo "Please run as root..."
fi

case "$1" in
	start)
		echo "Starting dwifid..."
		if [ -f /var/run/$NAME.pi ]
		then
			echo "Service already running..."
			exit 0
		fi
		nohup /usr/bin/dwifid 0<&- &>/home/mart/logfile &
		;;
	stop)
		echo "Stopping script..."
		kill "$(cat $PIDFILE)"
		rm -f $PIDFILE
		echo "Stopped succesfully..."
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $SCRIPTNAME {start|stop|restart}"
		;;
esac
exit 0
